name: fiitgn
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^3.1.0
  background_location: ^0.6.0
  cloud_firestore: ^2.2.1
  connectivity: ^3.0.6
  date_format: ^2.0.2
  firebase_core: ^1.2.1
  firebase_auth: ^1.3.0
  flutter_polyline_points: ^1.0.0
  flutter_map:
  flutter_signin_button: ^1.1.0
  font_awesome_flutter: ^8.9.0
  form_field_validator: ^1.0.1
  googleapis_auth: ^1.1.0
  googleapis: ^3.0.0
  google_maps_flutter: ^2.0.6
  google_sign_in: ^4.4.4
  http: ^0.13.3
  intl: ^0.17.0
  latlng: any
  location: ^2.3.5
  pedometer: ^2.0.2
  percent_indicator: ^2.1.7+4
  provider: ^4.3.2+2
  sensors: ^0.4.2+6
  shared_preferences: ^2.0.6
  stop_watch_timer: ^0.7.0
  url_launcher: ^6.0.8

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^6.0.0
  firebase_messaging: ^10.0.2
  firebase_messaging_web: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/iitgnLogo.png
    - assets/iitgnlogo-emblem.png
    - assets/distance.png
    - assets/runTile.jpg
    - assets/statsTile1.png
    - assets/fitGif.gif
    - assets/runMan.png
    - assets/chinUp.gif
    - assets/jumpingJack.gif
    - assets/jumpSquats.jpeg
    - assets/pushUp.gif
    - assets/Workout.gif
    - assets/WorkoutStats.png
    - assets/iitgnMess.jpg
    - assets/WorkoutStats2.gif
    - assets/Situps.jpeg
    - assets/MountainClimbers.gif
    - assets/Deadlift.gif
    - assets/fitnessPlan.jpg
    - assets/fitnessPlan2.jpg
    - assets/pushUp.jpg
    - assets/MountainClimbers.jpeg
    - assets/Deadlift.jpeg
    - assets/jumpingJack.jpg
    - assets/Workout.jpeg
    - assets/statsTile2.jpeg
    - assets/WorkoutStats3.jpeg
    - assets/newActivity.jpeg
    - assets/yourRunsblur.jpg
    - assets/yourWorkblurr.jpg
    - assets/runBud.jpg
    - assets/iitgnCamp.jpg
    - assets/homePage.jpg
    - assets/4805.png
    - assets/6517.png
    - assets/10765.png
    - assets/11241.png
    - assets/6569.png
    - assets/statLady.png
    - assets/cyclingStats.jpg
    - assets/clok.png
    - assets/hiss.png
    - assets/idea.png
    - assets/wiss.png
    - assets/23.png
    - assets/24.png
    - assets/ico.png
    - assets/foot.png
    - assets/tt.png
    - assets/squash.png
    - assets/empty.png
    - assets/toaster.png
    - assets/sandwich.png
    - assets/coffee-bean.png
    - assets/cutlery.png
    - assets/acti.png
    - assets/alloc.png
    - assets/food.png
    - assets/roonn.png
    - assets/twerkout.png
    - assets/admin.png
    - assets/act.png
    - assets/stats.png
    - assets/geddam.jpeg
    - assets/reesab.jpg
    - assets/aditya.jpg
    - assets/gottam.jpg
    - assets/rooben.jpg
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
    - family: LemonMilk
      fonts:
        - asset: assets/fonts/LEMONMILK-Light.otf
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Light.otf
    - family: Gro
      fonts:
        - asset: assets/fonts/NeutraText-Book.otf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
